# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\matthew.tran\CryptographyTheory-HUST\menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CryptographyTheory(object):
    def setupUi(self, CryptographyTheory):
        CryptographyTheory.setObjectName("CryptographyTheory")
        CryptographyTheory.resize(1347, 861)
        self.team_label = QtWidgets.QLabel(CryptographyTheory)
        self.team_label.setGeometry(QtCore.QRect(220, 140, 881, 111))
        self.team_label.setStyleSheet("color: #014023;\n"
"font: bold")
        self.team_label.setObjectName("team_label")
        self.en_button = QtWidgets.QPushButton(CryptographyTheory)
        self.en_button.setGeometry(QtCore.QRect(560, 580, 231, 71))
        self.en_button.setStyleSheet("color: rgb(0, 0, 127);\n"
"font-size: 15pt;\n"
"font: bold")
        self.en_button.setObjectName("en_button")
        self.team_label_2 = QtWidgets.QLabel(CryptographyTheory)
        self.team_label_2.setGeometry(QtCore.QRect(340, 250, 671, 61))
        self.team_label_2.setStyleSheet("color:#D98E04;\n"
"font: bold;\n"
"font-size: 15pt")
        self.team_label_2.setObjectName("team_label_2")
        self.label = QtWidgets.QLabel(CryptographyTheory)
        self.label.setGeometry(QtCore.QRect(510, 310, 371, 31))
        self.label.setStyleSheet("color:#025959;\n"
"font: bold;\n"
"font-size: 15pt")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(CryptographyTheory)
        self.label_2.setGeometry(QtCore.QRect(510, 360, 411, 31))
        self.label_2.setStyleSheet("color:#025959;\n"
"font: bold;\n"
"font-size: 15pt")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(CryptographyTheory)
        self.label_3.setGeometry(QtCore.QRect(510, 410, 441, 31))
        self.label_3.setStyleSheet("color:#025959;\n"
"font: bold;\n"
"font-size: 15pt")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(CryptographyTheory)
        self.label_4.setGeometry(QtCore.QRect(510, 460, 421, 31))
        self.label_4.setStyleSheet("color:#025959;\n"
"font: bold;\n"
"font-size: 15pt")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(CryptographyTheory)
        self.label_5.setGeometry(QtCore.QRect(510, 510, 431, 31))
        self.label_5.setStyleSheet("color:#025959;\n"
"font: bold;\n"
"font-size: 15pt")
        self.label_5.setObjectName("label_5")

        self.retranslateUi(CryptographyTheory)
        QtCore.QMetaObject.connectSlotsByName(CryptographyTheory)

    def retranslateUi(self, CryptographyTheory):
        _translate = QtCore.QCoreApplication.translate
        CryptographyTheory.setWindowTitle(_translate("CryptographyTheory", "Dialog"))
        self.team_label.setText(_translate("CryptographyTheory", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">Cryptography Theory - Team14</span></p></body></html>"))
        self.en_button.setText(_translate("CryptographyTheory", "Encrypt"))
        self.team_label_2.setText(_translate("CryptographyTheory", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Class: 137306 - Teacher: Do Trong Tuan</span></p></body></html>"))
        self.label.setText(_translate("CryptographyTheory", "1. Ha Hoang 20192866"))
        self.label_2.setText(_translate("CryptographyTheory", "2. Tran Nha Hoang 20192876"))
        self.label_3.setText(_translate("CryptographyTheory", "3. Nguyen Đuc An 20192675"))
        self.label_4.setText(_translate("CryptographyTheory", "4. Doan Minh Hiep 20192834"))
        self.label_5.setText(_translate("CryptographyTheory", "5. Nguyen Xuan Đuc 20192784"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CryptographyTheory = QtWidgets.QDialog()
    ui = Ui_CryptographyTheory()
    ui.setupUi(CryptographyTheory)
    CryptographyTheory.show()
    sys.exit(app.exec_())
